### ISSUE TITLE
expected np.ndarray (got int)

### ISSUE THREAD

**Issue by deniaud** [ExponentialML/ComfyUI_ELLA#9]
Hi, I have the latest version of ComfyUI, I updated transformers and other dependencies to the latest versions as well, but it didn't help. expected np.ndarray (got int) - in Encode node anyway

Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.09it/s]
!!! Exception during processing !!!
Traceback (most recent call last):
  File "E:\SD\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\SD\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\SD\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\SD\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_ELLA\ella.py", line 100, in encode
    cond_ella = ella(cond, timesteps=torch.from_numpy(sigma))
                                     ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected np.ndarray (got int)

**Comment by deniaud** [comment]
fix with add this code to 105 lines ella.py:

```
import numpy as np
sigma = np.array(sigma)
```
